### ISSUE TITLE
Recursive grammar rules

### ISSUE THREAD

**Issue by VladyslavNesterovskyi** [garfix/nli-go#3]
I have a question regarding this file :doc/manual/knowledge-engineer/howto.md.
It starts by describing a way to parse a name that consists of 2 or 3 nouns.
Can it be done a bit differently to support N nouns?
Like this, using recursion:
{ rule: proper_noun_group(N1) -> proper_noun(N1) proper_noun_group(N1)}
{ rule: proper_noun_group(N1) -> proper_noun(N1)}

{ rule: np(E1) -> proper_noun_group(E1) }

**Comment by garfix** [comment]
No, this is not a good idea, and I will try to explain why :)

The sequence of proper_noun()'s can be computationally very heavy, since it involves database lookups. By restricting them to two or three, the database is accessed as little as possible.

Any token may be a proper name, and I find out if a sequence of tokens is a full name by looking it up in the database. If I do not restrict it, any sequence of tokens is sent to the database to check if it happens to be a full name. You understand that this is expensive.

**Comment by VladyslavNesterovskyi** [comment]
Hm, ok, thanks for the explanation. I'll dig more to understand the code better.
