### ISSUE TITLE
Word lookup

### ISSUE THREAD

**Issue by VladyslavNesterovskyi** [garfix/nli-go#4]
Hello.

I have a question regarding grammar parsing. Currently, proper_noun is the only way to specify an unexpected word in the incoming sentence, right? Is it possible to extend it the way that work lookup is done in a separate database using something similar to NameResolver?
For example, we could specify predefined syntax nodes like "noun", "verb", "adj" and similar, reference them in grammar, and move actual words out of grammar file?
The reason I'm talking about this - what if we want to be able to understand whole language? It would make an enormous grammar file that would contain all possible words in a language.
But if we could move words out of grammar file in some kind of fast in-memory database and use word lookup to get it's possible sentence meanings?
Like we have the word "wish" - it could be a noun and could be a verb, and we would be able to try to match both meanings of the word to our grammar.

I hope I managed to explain it, sorry for the messy text. The main idea is to make grammar extensible and more lightweight.

Regards, Vladyslav.

**Comment by VladyslavNesterovskyi** [comment]
Hm, probably it would be clearer to say that what I suggest is to make terminal symbols in grammar predefined (noun, verb, etc), and when building a syntax tree from a sentence, lookup for possible sentence part of each word in the sentence, and then match each combination of the translated incoming sentence to our grammar.

for example, we have sentence
An apple is a fruit.
Which would be translated as "article noun verb article noun" (and some other combinations), and each sentence part is actually a terminal symbol in our grammar, so we can try to match this set of terminal symbols to our grammar to build syntax tree.

**Comment by garfix** [comment]
Hello Vladyslav,

I am not sure I completely understand what you mean, but I will take the different parts of your question and try to answer them as best as I can:

> Currently, proper_noun is the only way to specify an unexpected word in the incoming sentence, right?

`proper_noun` is the only way to treat words (names of people and things) that are located in the database. There is also a way to specify "open-ended categories" like numbers, e-mail addresses, postcodes, etc. namely via regular expressions as `number(N1) -> /^[0-9]+$/`

> But if we could move words out of grammar file in some kind of fast in-memory database and use word lookup to get it's possible sentence meanings?

I think you mean a lexicon, a file with word-forms, parts-of-speech (noun, verb) and sense. As it so happens, I used a lexicon before and I just removed it recently. The main reason was that many words take up two or more tokens (like "pick up", "give X to Y"). I could not place these in the lexicon so they had to go in the grammar anyway. Also I noticed that language has many forms that have no proper part-of-speech, like the possessive marker `'s` and even the question mark `?`. And there are the combinations with `have` and `be`, like "have children", where the word "have" in itself has no meaning. And then there are many idioms for which proper syntactic form is known, or if it is, it is strained. I found myself using the field "part-of-speech' for things it wasn't intended.

As for speed, this was my concern as well: wouldn't the grammar slow down with many more rules? I found out that this was not necessarily so. I could do some quick checks and thereby eliminate many of these rules; I can do a lot more optimizations if needed. At present the parser is very very fast, and it is so by design (being an Earley parser).

As for the grammar becoming crowded: you might think of placing the "lexicon" rules simply in a separate grammar file. Multiple grammar files are possible.


> Hm, probably it would be clearer to say that what I suggest is to make terminal symbols in grammar predefined (noun, verb, etc),

I don't want to restrict the parts-of-speech, because I want the grammar to allow for semantic-grammar constructs, if the user wants or needs them. A combination of traditional parts-of-speech, combined with some semantic-grammar phrases is optimal for an extendible and yet compact grammar, I believe.

> what if we want to be able to understand whole language? It would make an enormous grammar file that would contain all possible words in a language.

This is a noble goal, but it is not one which you or I need to be persuing at the moment. Try to keep the grammar simple to serve its purpose in the application. Creating a grammar that spans the entire language is something that one very few people have tried, and it is very very hard. And that is "only" the syntactic part.

I hope this answers some aspects of your question.

**Comment by VladyslavNesterovskyi** [comment]
Yes, thank you very much for the explanation, now I see...
Originally I had this idea about having a separate place for known words for a long time, but you're right, we have to store sense for them as well, and actually multiple grammar files can serve this purpose fine.

What do you think about the idea to make grammar extensible in runtime? So one could teach the system when it's online. It's a complicated topic, but I believe that's the only way one can make the system truly generic.
From the NLI-GO perspective that would mean adding an API to validate and modify grammar rules and reload them in memory.
Maybe for the first time, it would just mean to create a tool for someone who knows English grammar well could work as a knowledge engineer but without access to the original grammar files.

**Comment by garfix** [comment]
The grammar in the system is just an object of class Grammar, which has an `AddRule()` function. So extending the grammar while the system is running is simple in itself.

Adding an API, like a REST API, seems to presume that the system is a permanently running service to which one can send requests. NLI-GO is currently just a simple executable program that loads and parses all of its system files each time a new question is presented to it. This is because the only public use case I currently have for it is the DBpedia demo. This web app sends Ajax requests to a PHP process on the server. This PHP script calls the executable, and it returns a JSON string. State between requests is stored by the system in session files.

I have no plans to create an authoring environment for the system, I will leave that up to you (or anyone else interested). I quite like the idea of turning the system into a service; it would be nice if this could be done cross-platform, in the spirit of Go. But the exact nature of such a service needs to be worked out.

**Comment by VladyslavNesterovskyi** [comment]
Thanks for the tip. Yeah, creating a REST API or something similar is not the purpose of this library - it represents domain natural language processing logic.
